name: Archival
on:
  schedule:
    - cron: 0 * * * *

jobs:
  Archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Install Python
        run: sudo apt install python3
      - name: Install Waybackpy
        run: pip install waybackpy -U
      - name: Run run.py
        run: python3 run.py
          
        
