name: Archival
on:
  push:
  schedule:
    - cron: 0 * * * *

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        run: sudo apt install python3
      - name: Install Waybackpy
        run: pip install waybackpy -U
          
        
