name: Archival
on:
  push:
  schedule:
    - cron: 0 * * * *

jobs:
  Archive:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        run: sudo apt install python3
      - name: Install Waybackpy
        run: pip install waybackpy -U
      - name: List Directory
        run: ls
          
        
